### ISSUE TITLE
Bad type on operand stack

### ISSUE THREAD

**Issue by yooouuri** [blackdoor/hate#19] opened 2018-05-07 10:19 UTC
Model

```kotlin
package com.kwetter.models

import black.door.hate.HalRepresentation
import black.door.hate.HalResource

import java.io.Serializable
import java.net.URI
import java.util.*
import javax.json.bind.annotation.JsonbProperty
import javax.json.bind.annotation.JsonbTransient
import javax.persistence.*

@Entity
@Table(name = "tweets")
data class Tweet(
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        var id: Long? = null,
        var text: String,
        var date: Date) : HalResource, Serializable {
    override fun representationBuilder(): HalRepresentation.HalRepresentationBuilder {
        return HalRepresentation.builder()
                .addProperty("id", id)
                .addProperty("text", text)
                .addProperty("data", date)
                .addProperty("username", username())
                .addProperty("profile_image", profileImage())
                .addLink("self", this)
    }

    override fun location(): URI {
        return URI("/api/tweets/{$id}")
    }

    @JsonbTransient
    @ManyToOne(fetch = FetchType.EAGER)
    lateinit var user: User

    @JsonbProperty("username")
    fun username(): String {
        return user.username
    }

    @JsonbProperty("profile_image")
    fun profileImage(): String {
        return user.image
    }

    constructor(text: String, date: Date) : this(null, text, date)
}
```

Error
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/fasterxml/jackson/databind/SerializerProvider.<init>(Lcom/fasterxml/jackson/databind/SerializerProvider;)V @15: putfield
  Reason:
    Type 'com/fasterxml/jackson/databind/ser/std/NullSerializer' (current frame, stack[1]) is not assignable to 'com/fasterxml/jackson/databind/JsonSerializer'
  Current Frame:
    bci: @15
    flags: { }
    locals: { 'com/fasterxml/jackson/databind/SerializerProvider', 'com/fasterxml/jackson/databind/SerializerProvider' }
    stack: { 'com/fasterxml/jackson/databind/SerializerProvider', 'com/fasterxml/jackson/databind/ser/std/NullSerializer' }
  Bytecode:
    0x0000000: 2ab7 0001 2ab2 0002 b500 032a b200 04b5
    0x0000010: 0005 2ab2 0006 b500 072a 01b5 0008 2a01
    0x0000020: b500 0e2a 01b5 0009 2a01 b500 0d2a bb00
    0x0000030: 0a59 b700 0bb5 000c 2a2b b400 03b5 0003
    0x0000040: 2a2b b400 11b5 0011 2a2b b400 05b5 0005
    0x0000050: 2a2b b400 07b5 0007 2a2b b400 10b5 0010
    0x0000060: b1    
```

Endpoint

```kotlin
...
    @GET
    @Path("/{id}")
    fun single(@PathParam("id") id: Long): HalRepresentation {

        val tweet = tweetService.find(id)

        val hal = tweet.asEmbedded()

        return hal
    }
...
```

I'm using kotlin btw

**Comment by kag0** [comment] 2018-05-07 21:38
This looks like a tricky one.
My guess is either an incompatible jackson version somewhere, or a reflection issue.
Can you 

1. report what jackson version you're using
2. try using jackson 2.7.5 and report if the issue continues
3. include any line numbers from the stacktrace showing where this might have occurred in the hate or jackson libraries (or just let me know if you have an idea where it might be (step through debugging might help))
4. confirm you're not deserializing, dependency injecting, or otherwise trying to set a field with a jackson type using reflection somewhere?

**Comment by kag0** [comment] 2018-12-20 06:35
Closing this because I'm not able to reproduce.

**Closed by kag0** 2018-12-20 06:35 UTC
